apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vpro-ingress
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:  # ← Correct! Same level as metadata
  ingressClassName: nginx
  rules:
  - host: vprofile.hkhinfotech.xyz  # ← Added dash for list item
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vproapp-service
            port:
              number: 8080
