apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-pv-claim
  labels:
    app: vprodb
spec:
  accessModes:
    - ReadWriteOnce # Can be mounted read-write by a single node
  resources:
    requests:
      storage: 3Gi
  storageClassName: default

